//Delete Button and Dialog is keeping  hidden. next requirement is to show delete button and dialog for IT Admin only.

//frontend/app/dashboard/urgent/list/page.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import {
    AlertTriangle,
    CheckCircle2,
    ChevronDown,
    Clock,
    Eye,
    FileSpreadsheet,
    FileText,
    ListTodo,
    Loader2,
    Plus,
    Pencil,
    Save,
    Search,
    Trash2,
    UserRound,
    X,
    Zap,
} from "lucide-react";

import { Input } from "@/components/ui/input";
import {
    authApi,
    dashboardApi,
    type AuthMeData,
    type TroubleTicketITPersonnel,
} from "@/lib/api";
import {
    urgentTaskApi,
    type UrgentTask,
    type UrgentTaskPriority,
    type UrgentTaskStatus,
} from "@/lib/urgent-task-api";

const statusConfig: Record<
    UrgentTaskStatus,
    { color: string; bg: string; activeBg: string; icon: React.ReactNode }
> = {
    Pending: {
        color: "text-amber-700",
        bg: "bg-amber-50 border-amber-200",
        activeBg: "bg-amber-500 text-white border-amber-500",
        icon: <Clock size={10} />,
    },
    "In Progress": {
        color: "text-blue-700",
        bg: "bg-blue-50 border-blue-200",
        activeBg: "bg-blue-500 text-white border-blue-500",
        icon: <Zap size={10} />,
    },
    Completed: {
        color: "text-emerald-700",
        bg: "bg-emerald-50 border-emerald-200",
        activeBg: "bg-emerald-500 text-white border-emerald-500",
        icon: <CheckCircle2 size={10} />,
    },
};

const priorityConfig: Record<
    UrgentTaskPriority,
    { color: string; bg: string; activeBg: string; dot: string }
> = {
    Critical: {
        color: "text-red-700",
        bg: "bg-red-50 border-red-200",
        activeBg: "bg-red-500 text-white border-red-500",
        dot: "bg-red-500",
    },
    High: {
        color: "text-orange-700",
        bg: "bg-orange-50 border-orange-200",
        activeBg: "bg-orange-500 text-white border-orange-500",
        dot: "bg-orange-500",
    },
    Medium: {
        color: "text-yellow-700",
        bg: "bg-yellow-50 border-yellow-200",
        activeBg: "bg-yellow-500 text-white border-yellow-500",
        dot: "bg-yellow-500",
    },
    Low: {
        color: "text-green-700",
        bg: "bg-green-50 border-green-200",
        activeBg: "bg-green-500 text-white border-green-500",
        dot: "bg-green-500",
    },
};

function Avatar({ name }: { name: string }) {
    const initials = name
        .split(" ")
        .map((part) => part[0])
        .slice(0, 2)
        .join("")
        .toUpperCase();

    return (
        <span className="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-blue-100 bg-blue-50 text-[9px] font-bold text-blue-700">
            {initials || "?"}
        </span>
    );
}

function formatDate(value: string) {
    if (!value) return "—";
    const date = new Date(`${value}T00:00:00`);
    if (Number.isNaN(date.getTime())) return value;
    return new Intl.DateTimeFormat("en-GB", {
        day: "2-digit",
        month: "short",
        year: "numeric",
    }).format(date);
}

function exportToCSV(data: UrgentTask[]) {
    const headers = [
        "SL",
        "Reference",
        "Title",
        "Assigned To",
        "Generated By",
        "Due Date",
        "Status",
        "Priority",
        "Description",
    ];

    const rows = data.map((task, index) => [
        index + 1,
        task.reference,
        task.title,
        `${task.assigned_to_name} (${task.assigned_to})`,
        `${task.generated_by_name} (${task.generated_by})`,
        task.due_date,
        task.status,
        task.priority,
        task.description,
    ]);

    const csv = [headers, ...rows]
        .map((row) =>
            row
                .map((cell) => `"${String(cell ?? "").replace(/"/g, '""')}"`)
                .join(",")
        )
        .join("\n");

    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `urgent-tasks-${new Date().toISOString().slice(0, 10)}.csv`;
    anchor.click();
    URL.revokeObjectURL(url);
}

function exportToPDF(data: UrgentTask[]) {
    const rows = data
        .map(
            (task, index) => `
                <tr>
                    <td>${index + 1}</td>
                    <td>${task.reference}</td>
                    <td>${task.title}</td>
                    <td>${task.assigned_to_name}</td>
                    <td>${task.generated_by_name}</td>
                    <td>${task.due_date}</td>
                    <td>${task.status}</td>
                    <td>${task.priority}</td>
                </tr>`
        )
        .join("");

    const html = `<!DOCTYPE html>
    <html><head><meta charset="utf-8"/><title>Urgent Tasks Report</title>
    <style>
    body{font-family:Arial,sans-serif;font-size:11px;padding:24px;color:#111}
    h2{font-size:16px;margin-bottom:4px}.sub{color:#666;font-size:10px;margin-bottom:16px}
    table{width:100%;border-collapse:collapse}th{background:#f1f5f9;text-align:left;padding:8px;font-size:9px;text-transform:uppercase;border-bottom:2px solid #e2e8f0}
    td{padding:7px 8px;border-bottom:1px solid #e2e8f0;vertical-align:top}tr:nth-child(even) td{background:#f8fafc}
    </style></head><body>
    <h2>Urgent Tasks Report</h2><p class="sub">Generated ${new Date().toLocaleString()} · ${data.length} tasks</p>
    <table><thead><tr><th>#</th><th>Reference</th><th>Task</th><th>Assigned</th><th>Generated By</th><th>Due</th><th>Status</th><th>Priority</th></tr></thead><tbody>${rows}</tbody></table>
    </body></html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    win?.addEventListener("load", () => {
        win.print();
        URL.revokeObjectURL(url);
    });
}

export default function UrgentTaskPage() {
    const router = useRouter();
    const [tasks, setTasks] = useState<UrgentTask[]>([]);
    const [total, setTotal] = useState(0);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");
    const [search, setSearch] = useState("");
    const [activeStatus, setActiveStatus] = useState<UrgentTaskStatus | null>(null);
    const [activePriority, setActivePriority] = useState<UrgentTaskPriority | null>(null);
    const [selected, setSelected] = useState<UrgentTask | null>(null);
    const [authUser, setAuthUser] = useState<AuthMeData | null>(null);
    const [completingTaskId, setCompletingTaskId] = useState<number | null>(null);
    const [editingTask, setEditingTask] = useState<UrgentTask | null>(null);
    const [pendingCompleteTask, setPendingCompleteTask] = useState<UrgentTask | null>(null);
    const [pendingDeleteTask, setPendingDeleteTask] = useState<UrgentTask | null>(null);
    const [deletingTaskId, setDeletingTaskId] = useState<number | null>(null);
    const [itPersonnel, setITPersonnel] = useState<TroubleTicketITPersonnel[]>([]);

    const canCompleteUrgentTask =
        String(authUser?.role_code ?? "")
            .trim()
            .toUpperCase() === "IT_ADMIN";

    async function loadTasks() {
        try {
            setLoading(true);
            setError("");
            const response = await urgentTaskApi.list({
                page: 1,
                limit: 200,
            });
            setTasks(response.data ?? []);
            setTotal(Number(response.total ?? response.data?.length ?? 0));
        } catch (reason) {
            setTasks([]);
            setTotal(0);
            setError(
                reason instanceof Error
                    ? reason.message
                    : "Unable to load urgent tasks."
            );
        } finally {
            setLoading(false);
        }
    }

    useEffect(() => {
        let active = true;

        async function loadActionContext() {
            try {
                const [
                    authResponse,
                    personnelResponse,
                ] = await Promise.all([
                    authApi.me(),
                    dashboardApi.troubleTicketITPersonnel(),
                ]);

                if (!active) {
                    return;
                }

                setAuthUser(
                    authResponse.data ?? null
                );

                setITPersonnel(
                    personnelResponse.data ?? []
                );
            } catch (reason) {
                console.error(
                    "Unable to load urgent-task action context:",
                    reason
                );

                if (active) {
                    setAuthUser(null);
                    setITPersonnel([]);
                }
            }
        }

        void loadActionContext();

        return () => {
            active = false;
        };
    }, []);

    useEffect(() => {
        void loadTasks();
    }, []);

    const filtered = useMemo(() => {
        const q = search.trim().toLowerCase();
        return tasks.filter((item) => {
            const matchSearch =
                !q ||
                item.reference.toLowerCase().includes(q) ||
                item.title.toLowerCase().includes(q) ||
                item.description.toLowerCase().includes(q) ||
                item.assigned_to.toLowerCase().includes(q) ||
                item.assigned_to_name.toLowerCase().includes(q) ||
                item.generated_by_name.toLowerCase().includes(q);

            const matchStatus = !activeStatus || item.status === activeStatus;
            const matchPriority = !activePriority || item.priority === activePriority;
            return matchSearch && matchStatus && matchPriority;
        });
    }, [tasks, search, activeStatus, activePriority]);

    const counts = useMemo(
        () => ({
            total: tasks.length,
            pending: tasks.filter((task) => task.status === "Pending").length,
            inProgress: tasks.filter((task) => task.status === "In Progress").length,
            completed: tasks.filter((task) => task.status === "Completed").length,
        }),
        [tasks]
    );

    async function handleCompleteConfirmed() {
        const task = pendingCompleteTask;

        if (!task) {
            return;
        }

        if (!canCompleteUrgentTask) {
            setError(
                "Only an IT Administrator can complete an urgent task."
            );
            setPendingCompleteTask(null);
            return;
        }

        try {
            setCompletingTaskId(task.id);
            setError("");

            await urgentTaskApi.complete(task.id);
            await loadTasks();

            if (selected?.id === task.id) {
                setSelected(null);
            }

            setPendingCompleteTask(null);
        } catch (reason) {
            setError(
                reason instanceof Error
                    ? reason.message
                    : "Unable to complete urgent task."
            );
        } finally {
            setCompletingTaskId(null);
        }
    }

    async function handleDeleteConfirmed() {
        const task = pendingDeleteTask;

        if (!task) {
            return;
        }

        try {
            setDeletingTaskId(task.id);
            setError("");
            await urgentTaskApi.remove(task.id);
            await loadTasks();
            setPendingDeleteTask(null);
        } catch (reason) {
            setError(
                reason instanceof Error
                    ? reason.message
                    : "Unable to delete urgent task."
            );
        } finally {
            setDeletingTaskId(null);
        }
    }

    function clearFilters() {
        setSearch("");
        setActiveStatus(null);
        setActivePriority(null);
    }

    const hasFilters = Boolean(search || activeStatus || activePriority);

    return (
        <div className="space-y-4 p-4 sm:p-6">
            <div className="rounded-2xl border border-border bg-card p-5 shadow-sm">
                <div className="flex flex-wrap items-start justify-between gap-3">
                    <div className="flex items-center gap-3">
                        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-red-100 bg-red-50">
                            <ListTodo className="h-5 w-5 text-red-600" />
                        </div>
                        <div>
                            <h1 className="text-sm font-bold text-foreground">Urgent Tasks</h1>
                            <p className="mt-0.5 text-xs text-muted-foreground">
                                Live operational tasks from PostgreSQL with authenticated creator audit data.
                            </p>
                        </div>
                    </div>

                    <div className="flex flex-wrap gap-2">
                        <button
                            onClick={() => router.push("/dashboard/urgent/create")}
                            className="flex items-center gap-1.5 rounded-lg border border-blue-600 bg-blue-600 px-3 py-1.5 text-xs font-semibold text-white transition hover:bg-blue-700"
                        >
                            <Plus size={13} /> New Task
                        </button>
                        <button
                            onClick={() => exportToCSV(filtered)}
                            className="flex items-center gap-1.5 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-700 transition hover:bg-emerald-100"
                        >
                            <FileSpreadsheet size={13} /> Excel
                        </button>
                        <button
                            onClick={() => exportToPDF(filtered)}
                            className="flex items-center gap-1.5 rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 text-xs font-medium text-red-700 transition hover:bg-red-100"
                        >
                            <FileText size={13} /> PDF
                        </button>
                    </div>
                </div>

                <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
                    {[
                        { label: "Total Tasks", value: counts.total, status: null, bg: "bg-muted border-border", color: "text-foreground" },
                        { label: "Pending", value: counts.pending, status: "Pending" as UrgentTaskStatus, bg: "bg-amber-50 border-amber-100", color: "text-amber-700" },
                        { label: "In Progress", value: counts.inProgress, status: "In Progress" as UrgentTaskStatus, bg: "bg-blue-50 border-blue-100", color: "text-blue-700" },
                        { label: "Completed", value: counts.completed, status: "Completed" as UrgentTaskStatus, bg: "bg-emerald-50 border-emerald-100", color: "text-emerald-700" },
                    ].map((item) => (
                        <button
                            key={item.label}
                            onClick={() =>
                                setActiveStatus(
                                    item.status && activeStatus === item.status
                                        ? null
                                        : item.status
                                )
                            }
                            className={`rounded-xl border px-4 py-3 text-left transition hover:opacity-85 ${item.bg} ${item.status && activeStatus === item.status
                                ? "ring-2 ring-primary"
                                : "ring-2 ring-transparent"
                                }`}
                        >
                            <p className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
                                {item.label}
                            </p>
                            <p className={`mt-0.5 text-xl font-bold ${item.color}`}>
                                {item.value}
                            </p>
                        </button>
                    ))}
                </div>
            </div>

            <div className="flex flex-wrap items-center gap-3 rounded-xl border border-border bg-card px-4 py-3 shadow-sm">
                <p className="shrink-0 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
                    Priority
                </p>
                <div className="flex flex-wrap gap-2">
                    {(Object.keys(priorityConfig) as UrgentTaskPriority[]).map((level) => {
                        const cfg = priorityConfig[level];
                        const active = activePriority === level;
                        return (
                            <button
                                key={level}
                                onClick={() => setActivePriority(active ? null : level)}
                                className={`flex items-center gap-1.5 rounded-lg border px-2.5 py-1 text-[11px] font-semibold transition ${active ? cfg.activeBg : `${cfg.bg} ${cfg.color}`
                                    }`}
                            >
                                <span className={`h-1.5 w-1.5 rounded-full ${active ? "bg-white/80" : cfg.dot}`} />
                                {level}
                                <span className={active ? "opacity-70" : "opacity-50"}>
                                    {tasks.filter((task) => task.priority === level).length}
                                </span>
                            </button>
                        );
                    })}
                </div>
                {tasks.some((task) => task.priority === "Critical" && task.status !== "Completed") && (
                    <span className="ml-auto flex items-center gap-1 text-[11px] font-semibold text-red-600">
                        <AlertTriangle size={11} />
                        {tasks.filter((task) => task.priority === "Critical" && task.status !== "Completed").length} active critical
                    </span>
                )}
            </div>

            <div className="overflow-visible rounded-xl border border-border bg-card shadow-sm">
                <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border px-4 py-3">
                    <div className="flex flex-wrap items-center gap-2">
                        <p className="text-[11px] text-muted-foreground">
                            Showing <span className="font-semibold text-foreground">{filtered.length}</span> of {total} tasks
                        </p>
                        {activeStatus && <FilterPill label={activeStatus} onClear={() => setActiveStatus(null)} />}
                        {activePriority && <FilterPill label={activePriority} onClear={() => setActivePriority(null)} />}
                        {hasFilters && (
                            <button onClick={clearFilters} className="text-[10px] text-muted-foreground underline hover:text-foreground">
                                Clear all
                            </button>
                        )}
                    </div>

                    <div className="relative">
                        <Search size={12} className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground" />
                        <Input
                            placeholder="Search reference, employee, creator, task..."
                            value={search}
                            onChange={(event) => setSearch(event.target.value)}
                            className="h-8 w-72 pl-7 text-xs"
                        />
                    </div>
                </div>

                {loading ? (
                    <div className="flex min-h-[260px] items-center justify-center gap-2 text-xs text-muted-foreground">
                        <Loader2 className="h-4 w-4 animate-spin" /> Loading urgent tasks...
                    </div>
                ) : error ? (
                    <div className="flex min-h-[260px] flex-col items-center justify-center gap-2 p-6 text-center text-xs text-red-600">
                        <AlertTriangle className="h-6 w-6" />
                        <p>{error}</p>
                        <button onClick={() => void loadTasks()} className="rounded-md border px-3 py-1 text-[11px] font-semibold">
                            Retry
                        </button>
                    </div>
                ) : (
                    <div className="w-full overflow-hidden rounded-b-xl">
                        <table className="w-full table-fixed">
                            <colgroup>
                                <col className="w-[4%]" />
                                <col className="w-[12%]" />
                                <col className="w-[22%]" />
                                <col className="w-[14%]" />
                                <col className="w-[14%]" />
                                <col className="w-[10%]" />
                                <col className="w-[9%]" />
                                <col className="w-[7%]" />
                                <col className="w-[8%]" />
                            </colgroup>

                            <thead className="border-b border-border bg-muted/50">
                                <tr>
                                    {["#", "Reference", "Task", "Assigned To", "Generated By", "Due Date", "Status", "Priority", "Actions"].map((column) => (
                                        <th key={column} className="px-2 py-2 text-left text-[9px] font-semibold uppercase tracking-[0.06em] text-muted-foreground">
                                            {column}
                                        </th>
                                    ))}
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-border/50">
                                {filtered.map((item, index) => (
                                    <tr
                                        key={item.id}
                                        className="h-14 transition-colors hover:bg-muted/30"
                                    >
                                        <td className="px-2 py-2 align-middle text-[10px] text-muted-foreground">{index + 1}</td>
                                        <td className="px-2 py-2 align-middle">
                                            <span className="block truncate rounded-md border border-blue-100 bg-blue-50 px-1.5 py-0.5 font-mono text-[9px] font-semibold text-blue-700">
                                                {item.reference}
                                            </span>
                                        </td>
                                        <td className="px-2 py-2 align-middle">
                                            <p className="truncate text-[10.5px] font-semibold text-foreground" title={item.title}>{item.title}</p>
                                            <p className="mt-0.5 truncate text-[9px] text-muted-foreground" title={item.description}>{item.description || "No description"}</p>
                                        </td>
                                        <td className="px-2 py-2 align-middle">
                                            <PersonCell id={item.assigned_to} name={item.assigned_to_name} />
                                        </td>
                                        <td className="px-2 py-2 align-middle">
                                            <PersonCell id={item.generated_by} name={item.generated_by_name} creator />
                                        </td>
                                        <td className="px-2 py-2 align-middle text-[9.5px] text-muted-foreground">{formatDate(item.due_date)}</td>
                                        <td className="px-2 py-2 align-middle"><StatusBadge status={item.status} /></td>
                                        <td className="px-2 py-2 align-middle"><PriorityBadge priority={item.priority} /></td>
                                        <td className="px-2 py-2 align-middle">
                                            <ActionsDropdown
                                                item={item}
                                                canManage={canCompleteUrgentTask}
                                                completing={
                                                    completingTaskId === item.id
                                                }
                                                openUp={
                                                    index >=
                                                    Math.max(
                                                        0,
                                                        filtered.length - 3
                                                    )
                                                }
                                                onView={() => setSelected(item)}
                                                onUpdate={() =>
                                                    setEditingTask(item)
                                                }
                                                onComplete={() =>
                                                    setPendingCompleteTask(item)
                                                }
                                                onDelete={() =>
                                                    setPendingDeleteTask(item)
                                                }
                                            />
                                        </td>
                                    </tr>
                                ))}
                                {filtered.length === 0 && (
                                    <tr>
                                        <td colSpan={9} className="py-12 text-center text-xs text-muted-foreground">
                                            No urgent tasks match the current filters.
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>

            {selected && (
                <TaskDetails
                    task={selected}
                    onClose={() =>
                        setSelected(null)
                    }
                />
            )}

            {editingTask && (
                <UpdateTaskDialog
                    task={editingTask}
                    personnel={itPersonnel}
                    onClose={() =>
                        setEditingTask(null)
                    }
                    onUpdated={async () => {
                        setEditingTask(null);
                        await loadTasks();
                    }}
                />
            )}

            {pendingCompleteTask && (
                <ConfirmActionDialog
                    tone="success"
                    title="Complete urgent task?"
                    description={
                        <>
                            Are you sure you want to mark
                            <span className="mx-1 font-mono font-semibold text-foreground">
                                {pendingCompleteTask.reference}
                            </span>
                            as completed?
                        </>
                    }
                    confirmLabel="Mark as Completed"
                    busyLabel="Completing..."
                    busy={
                        completingTaskId === pendingCompleteTask.id
                    }
                    onCancel={() =>
                        setPendingCompleteTask(null)
                    }
                    onConfirm={() =>
                        void handleCompleteConfirmed()
                    }
                />
            )}


            {/* Delete Confirmation Dialog */}
            {/* {pendingDeleteTask && (
                <ConfirmActionDialog
                    tone="danger"
                    title="Delete urgent task?"
                    description={
                        <>
                            Are you sure you want to delete
                            <span className="mx-1 font-mono font-semibold text-foreground">
                                {pendingDeleteTask.reference}
                            </span>
                            ?
                        </>
                    }
                    confirmLabel="Delete Task"
                    busyLabel="Deleting..."
                    busy={
                        deletingTaskId === pendingDeleteTask.id
                    }
                    onCancel={() =>
                        setPendingDeleteTask(null)
                    }
                    onConfirm={() =>
                        void handleDeleteConfirmed()
                    }
                />
            )} */}
        </div>
    );
}

function FilterPill({ label, onClear }: { label: string; onClear: () => void }) {
    return (
        <span className="flex items-center gap-1 rounded-full border border-primary/20 bg-primary/10 px-2 py-0.5 text-[10px] font-medium text-primary">
            {label}
            <button type="button" onClick={onClear}><X size={10} /></button>
        </span>
    );
}

function PersonCell({ id, name, creator = false }: { id: string; name: string; creator?: boolean }) {
    return (
        <div className="flex min-w-0 items-center gap-1.5">
            {creator ? (
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-violet-100 bg-violet-50 text-violet-700">
                    <UserRound size={12} />
                </span>
            ) : (
                <Avatar name={name} />
            )}
            <div className="min-w-0">
                <p className="truncate text-[9.5px] font-semibold text-foreground" title={name}>{name}</p>
                <p className="truncate font-mono text-[8px] text-muted-foreground">{id}</p>
            </div>
        </div>
    );
}

function StatusBadge({ status }: { status: UrgentTaskStatus }) {
    const cfg = statusConfig[status];
    return (
        <span className={`inline-flex items-center gap-1 rounded-full border px-1.5 py-0.5 text-[9px] font-semibold ${cfg.bg} ${cfg.color}`}>
            {cfg.icon} {status}
        </span>
    );
}

function PriorityBadge({ priority }: { priority: UrgentTaskPriority }) {
    const cfg = priorityConfig[priority];
    return (
        <span className={`inline-flex items-center gap-1 rounded-full border px-1.5 py-0.5 text-[9px] font-semibold ${cfg.bg} ${cfg.color}`}>
            <span className={`h-1.5 w-1.5 rounded-full ${cfg.dot}`} />
            {priority}
        </span>
    );
}

function ActionsDropdown({
    item,
    canManage,
    completing,
    openUp = false,
    onView,
    onUpdate,
    onComplete,
    onDelete,
}: {
    item: UrgentTask;
    canManage: boolean;
    completing: boolean;
    openUp?: boolean;
    onView: () => void;
    onUpdate: () => void;
    onComplete: () => void;
    onDelete: () => void;
}) {
    const [open, setOpen] =
        useState(false);

    const ref =
        useRef<HTMLDivElement>(null);

    useEffect(() => {
        const handler = (
            event: MouseEvent
        ) => {
            if (
                ref.current &&
                !ref.current.contains(
                    event.target as Node
                )
            ) {
                setOpen(false);
            }
        };

        document.addEventListener(
            "mousedown",
            handler
        );

        return () =>
            document.removeEventListener(
                "mousedown",
                handler
            );
    }, []);

    const isCompleted =
        item.status === "Completed";

    return (
        <div
            ref={ref}
            className="relative inline-block"
        >
            <button
                type="button"
                onClick={() =>
                    setOpen(!open)
                }
                className="flex items-center gap-1 rounded-lg border border-border bg-muted px-2 py-1 text-[9.5px] font-medium text-foreground transition hover:bg-border"
            >
                Actions
                <ChevronDown size={11} />
            </button>

            {open && (
                <div
                    className={`absolute right-0 z-[80] w-44 overflow-hidden rounded-xl border border-border bg-card py-1 shadow-xl ${openUp
                        ? "bottom-full mb-1"
                        : "top-full mt-1"
                        }`}
                >
                    <DropItem
                        icon={<Eye size={12} />}
                        label="View"
                        color="text-blue-600"
                        onClick={() => {
                            onView();
                            setOpen(false);
                        }}
                    />

                    {canManage &&
                        !isCompleted && (
                            <DropItem
                                icon={
                                    <Pencil
                                        size={12}
                                    />
                                }
                                label="Update"
                                color="text-violet-700"
                                onClick={() => {
                                    onUpdate();
                                    setOpen(false);
                                }}
                            />
                        )}

                    {canManage &&
                        !isCompleted && (
                            <DropItem
                                icon={
                                    completing ? (
                                        <Loader2
                                            size={12}
                                            className="animate-spin"
                                        />
                                    ) : (
                                        <CheckCircle2
                                            size={12}
                                        />
                                    )
                                }
                                label={
                                    completing
                                        ? "Completing..."
                                        : "Completed"
                                }
                                color="text-emerald-700"
                                disabled={
                                    completing
                                }
                                onClick={() => {
                                    if (
                                        completing
                                    ) {
                                        return;
                                    }

                                    onComplete();
                                    setOpen(false);
                                }}
                            />
                        )}

                    {/* {!isCompleted && (
                        <DropItem
                            icon={
                                <Trash2
                                    size={12}
                                />
                            }
                            label="Delete"
                            color="text-red-600"
                            onClick={() => {
                                onDelete();
                                setOpen(false);
                            }}
                        />
                    )} */}
                </div>
            )}
        </div>
    );
}

function DropItem({
    icon,
    label,
    color,
    disabled = false,
    onClick,
}: {
    icon: React.ReactNode;
    label: string;
    color: string;
    disabled?: boolean;
    onClick: () => void;
}) {
    return (
        <button
            type="button"
            disabled={disabled}
            onClick={onClick}
            className={`flex w-full items-center gap-2 px-3 py-1.5 text-[11px] font-medium transition hover:bg-muted disabled:cursor-not-allowed disabled:opacity-50 ${color}`}
        >
            {icon}
            {label}
        </button>
    );
}
function ConfirmActionDialog({
    tone,
    title,
    description,
    confirmLabel,
    busyLabel,
    busy,
    onCancel,
    onConfirm,
}: {
    tone: "success" | "danger";
    title: string;
    description: React.ReactNode;
    confirmLabel: string;
    busyLabel: string;
    busy: boolean;
    onCancel: () => void;
    onConfirm: () => void;
}) {
    const success = tone === "success";

    return (
        <div
            className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-[2px]"
            onMouseDown={() => {
                if (!busy) {
                    onCancel();
                }
            }}
        >
            <div
                role="dialog"
                aria-modal="true"
                aria-labelledby="urgent-action-dialog-title"
                className="w-full max-w-md overflow-hidden rounded-2xl border border-border bg-card shadow-2xl"
                onMouseDown={(event) => event.stopPropagation()}
            >
                <div className="flex items-start gap-3 px-5 pt-5">
                    <div
                        className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border ${success
                            ? "border-emerald-200 bg-emerald-50 text-emerald-700"
                            : "border-red-200 bg-red-50 text-red-700"
                            }`}
                    >
                        {success ? (
                            <CheckCircle2 className="h-5 w-5" />
                        ) : (
                            <AlertTriangle className="h-5 w-5" />
                        )}
                    </div>

                    <div className="min-w-0 flex-1">
                        <h2
                            id="urgent-action-dialog-title"
                            className="text-sm font-semibold text-foreground"
                        >
                            {title}
                        </h2>

                        <div className="mt-1.5 text-[11px] leading-5 text-muted-foreground">
                            {description}
                        </div>
                    </div>

                    <button
                        type="button"
                        disabled={busy}
                        onClick={onCancel}
                        className="rounded-lg p-1.5 text-muted-foreground transition hover:bg-muted hover:text-foreground disabled:opacity-50"
                        aria-label="Close confirmation dialog"
                    >
                        <X className="h-4 w-4" />
                    </button>
                </div>



                <div className="mt-5 flex items-center justify-end gap-2 border-t border-border bg-muted/15 px-5 py-3">
                    <button
                        type="button"
                        disabled={busy}
                        onClick={onCancel}
                        className="h-8 rounded-lg border border-border bg-background px-3 text-[10px] font-semibold text-foreground transition hover:bg-muted disabled:opacity-50"
                    >
                        Cancel
                    </button>

                    <button
                        type="button"
                        disabled={busy}
                        onClick={onConfirm}
                        className={`inline-flex h-8 min-w-[132px] items-center justify-center gap-1.5 rounded-lg px-3 text-[10px] font-semibold text-white transition disabled:cursor-not-allowed disabled:opacity-60 ${success
                            ? "bg-emerald-600 hover:bg-emerald-700"
                            : "bg-red-600 hover:bg-red-700"
                            }`}
                    >
                        {busy && (
                            <Loader2 className="h-3 w-3 animate-spin" />
                        )}
                        {busy ? busyLabel : confirmLabel}
                    </button>
                </div>
            </div>
        </div>
    );
}

function UpdateTaskDialog({
    task,
    personnel,
    onClose,
    onUpdated,
}: {
    task: UrgentTask;
    personnel:
    TroubleTicketITPersonnel[];
    onClose: () => void;
    onUpdated: () => Promise<void>;
}) {
    const [form, setForm] = useState({
        title: task.title,
        description:
            task.description ?? "",
        priority:
            task.priority,
        status:
            task.status === "Completed"
                ? ("In Progress" as UrgentTaskStatus)
                : task.status,
        dueDate:
            task.due_date,
        assignedTo:
            task.assigned_to,
    });

    const [saving, setSaving] =
        useState(false);

    const [formError, setFormError] =
        useState("");

    async function handleSubmit(
        event:
            React.FormEvent<HTMLFormElement>
    ) {
        event.preventDefault();

        const title =
            form.title.trim();

        if (
            title.length < 3 ||
            title.length > 180
        ) {
            setFormError(
                "Task title must be between 3 and 180 characters."
            );
            return;
        }

        if (!form.assignedTo) {
            setFormError(
                "Assigned To is required."
            );
            return;
        }

        if (!form.dueDate) {
            setFormError(
                "Due Date is required."
            );
            return;
        }

        try {
            setSaving(true);
            setFormError("");

            await urgentTaskApi.update(
                task.id,
                {
                    title,
                    description:
                        form.description.trim(),
                    priority:
                        form.priority,
                    status:
                        form.status,
                    due_date:
                        form.dueDate,
                    assigned_to:
                        form.assignedTo,
                }
            );

            await onUpdated();
        } catch (reason) {
            setFormError(
                reason instanceof Error
                    ? reason.message
                    : "Unable to update urgent task."
            );
        } finally {
            setSaving(false);
        }
    }

    return (
        <div
            className="fixed inset-0 z-[90] flex items-center justify-center bg-black/45 p-4"
            onMouseDown={() => {
                if (!saving) {
                    onClose();
                }
            }}
        >
            <form
                onSubmit={handleSubmit}
                className="w-full max-w-2xl overflow-hidden rounded-2xl border border-border bg-card shadow-2xl"
                onMouseDown={(event) =>
                    event.stopPropagation()
                }
            >
                <div className="flex items-start justify-between border-b border-border px-5 py-4">
                    <div>
                        <div className="flex items-center gap-2">
                            <span className="flex h-8 w-8 items-center justify-center rounded-lg border border-violet-100 bg-violet-50 text-violet-700">
                                <Pencil
                                    size={14}
                                />
                            </span>

                            <div>
                                <p className="font-mono text-[10px] font-semibold text-blue-600">
                                    {task.reference}
                                </p>

                                <h2 className="text-sm font-semibold text-foreground">
                                    Update Urgent Task
                                </h2>
                            </div>
                        </div>

                        <p className="mt-2 text-[10px] text-muted-foreground">
                            Update operational details. Completion remains a separate auditable action.
                        </p>
                    </div>

                    <button
                        type="button"
                        disabled={saving}
                        onClick={onClose}
                        className="rounded-lg p-1.5 text-muted-foreground transition hover:bg-muted hover:text-foreground disabled:opacity-50"
                        aria-label="Close update dialog"
                    >
                        <X size={16} />
                    </button>
                </div>

                <div className="grid gap-4 p-5 md:grid-cols-2">
                    <div className="space-y-4 md:col-span-2">
                        <div className="space-y-1.5">
                            <label className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                                Task Title *
                            </label>

                            <Input
                                value={
                                    form.title
                                }
                                maxLength={180}
                                onChange={(
                                    event
                                ) =>
                                    setForm(
                                        (
                                            previous
                                        ) => ({
                                            ...previous,
                                            title:
                                                event
                                                    .target
                                                    .value,
                                        })
                                    )
                                }
                                className="h-9 text-xs"
                            />

                            <div className="text-right text-[9px] text-muted-foreground">
                                {
                                    form.title
                                        .length
                                }
                                /180
                            </div>
                        </div>

                        <div className="space-y-1.5">
                            <label className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                                Description
                            </label>

                            <textarea
                                value={
                                    form.description
                                }
                                maxLength={5000}
                                rows={4}
                                onChange={(
                                    event
                                ) =>
                                    setForm(
                                        (
                                            previous
                                        ) => ({
                                            ...previous,
                                            description:
                                                event
                                                    .target
                                                    .value,
                                        })
                                    )
                                }
                                className="w-full resize-none rounded-lg border border-border bg-background px-3 py-2 text-xs text-foreground outline-none transition focus:border-primary/40 focus:ring-2 focus:ring-primary/10"
                                placeholder="Describe the work, dependency or operational context..."
                            />
                        </div>
                    </div>

                    <div className="space-y-1.5">
                        <label className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                            Assigned To *
                        </label>

                        <select
                            value={
                                form.assignedTo
                            }
                            onChange={(
                                event
                            ) =>
                                setForm(
                                    (
                                        previous
                                    ) => ({
                                        ...previous,
                                        assignedTo:
                                            event
                                                .target
                                                .value,
                                    })
                                )
                            }
                            className="h-9 w-full rounded-lg border border-border bg-background px-3 text-xs text-foreground outline-none transition focus:border-primary/40 focus:ring-2 focus:ring-primary/10"
                        >
                            <option value="">
                                Select active IT personnel
                            </option>

                            {personnel.map(
                                (
                                    person
                                ) => (
                                    <option
                                        key={
                                            person.employee_id
                                        }
                                        value={
                                            person.employee_id
                                        }
                                    >
                                        {
                                            person.employee_name
                                        }{" "}
                                        (
                                        {
                                            person.employee_id
                                        }
                                        )
                                    </option>
                                )
                            )}
                        </select>

                        <p className="text-[9px] text-muted-foreground">
                            Only active IT personnel are available.
                        </p>
                    </div>

                    <div className="space-y-1.5">
                        <label className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                            Due Date *
                        </label>

                        <Input
                            type="date"
                            value={
                                form.dueDate
                            }
                            onChange={(
                                event
                            ) =>
                                setForm(
                                    (
                                        previous
                                    ) => ({
                                        ...previous,
                                        dueDate:
                                            event
                                                .target
                                                .value,
                                    })
                                )
                            }
                            className="h-9 text-xs"
                        />
                    </div>

                    <div className="space-y-1.5">
                        <label className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                            Priority
                        </label>

                        <select
                            value={
                                form.priority
                            }
                            onChange={(
                                event
                            ) =>
                                setForm(
                                    (
                                        previous
                                    ) => ({
                                        ...previous,
                                        priority:
                                            event
                                                .target
                                                .value as UrgentTaskPriority,
                                    })
                                )
                            }
                            className="h-9 w-full rounded-lg border border-border bg-background px-3 text-xs text-foreground outline-none transition focus:border-primary/40 focus:ring-2 focus:ring-primary/10"
                        >
                            <option value="Critical">
                                Critical
                            </option>
                            <option value="High">
                                High
                            </option>
                            <option value="Medium">
                                Medium
                            </option>
                            <option value="Low">
                                Low
                            </option>
                        </select>
                    </div>

                    <div className="space-y-1.5">
                        <label className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                            Status
                        </label>

                        <select
                            value={
                                form.status
                            }
                            onChange={(
                                event
                            ) =>
                                setForm(
                                    (
                                        previous
                                    ) => ({
                                        ...previous,
                                        status:
                                            event
                                                .target
                                                .value as UrgentTaskStatus,
                                    })
                                )
                            }
                            className="h-9 w-full rounded-lg border border-border bg-background px-3 text-xs text-foreground outline-none transition focus:border-primary/40 focus:ring-2 focus:ring-primary/10"
                        >
                            <option value="Pending">
                                Pending
                            </option>
                            <option value="In Progress">
                                In Progress
                            </option>
                        </select>

                        <p className="text-[9px] text-muted-foreground">
                            Use the separate Completed action to close the task.
                        </p>
                    </div>

                    {formError && (
                        <div className="md:col-span-2 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-[10px] text-red-700">
                            <div className="flex items-start gap-2">
                                <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                                <span>
                                    {formError}
                                </span>
                            </div>
                        </div>
                    )}
                </div>

                <div className="flex items-center justify-between gap-3 border-t border-border bg-muted/20 px-5 py-3">
                    <p className="text-[9px] text-muted-foreground">
                        Update is restricted to IT Administrator and is enforced by the backend.
                    </p>

                    <div className="flex items-center gap-2">
                        <button
                            type="button"
                            disabled={saving}
                            onClick={onClose}
                            className="h-8 rounded-lg border border-border bg-background px-3 text-[10px] font-semibold text-foreground transition hover:bg-muted disabled:opacity-50"
                        >
                            Cancel
                        </button>

                        <button
                            type="submit"
                            disabled={saving}
                            className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-violet-600 bg-violet-600 px-3 text-[10px] font-semibold text-white transition hover:bg-violet-700 disabled:cursor-not-allowed disabled:opacity-60"
                        >
                            {saving ? (
                                <Loader2 className="h-3 w-3 animate-spin" />
                            ) : (
                                <Save className="h-3 w-3" />
                            )}

                            {saving
                                ? "Saving..."
                                : "Save Changes"}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    );
}


function TaskDetails({ task, onClose }: { task: UrgentTask; onClose: () => void }) {
    return (
        <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/45 p-4" onMouseDown={onClose}>
            <div className="w-full max-w-xl rounded-2xl border border-border bg-card shadow-2xl" onMouseDown={(event) => event.stopPropagation()}>
                <div className="flex items-start justify-between border-b border-border p-5">
                    <div>
                        <p className="font-mono text-[10px] font-semibold text-blue-600">{task.reference}</p>
                        <h2 className="mt-1 text-base font-semibold text-foreground">{task.title}</h2>
                    </div>
                    <button onClick={onClose} className="rounded-lg p-1.5 text-muted-foreground transition hover:bg-muted hover:text-foreground"><X size={16} /></button>
                </div>
                <div className="space-y-4 p-5">
                    <div className="grid grid-cols-2 gap-3">
                        <Detail label="Assigned To" value={`${task.assigned_to_name} (${task.assigned_to})`} />
                        <Detail label="Generated By" value={`${task.generated_by_name} (${task.generated_by})`} />
                        <Detail label="Due Date" value={formatDate(task.due_date)} />
                        <Detail label="Status / Priority" value={`${task.status} · ${task.priority}`} />
                    </div>
                    <div className="rounded-xl border border-border bg-muted/30 p-4">
                        <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Description</p>
                        <p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-foreground">{task.description || "No description provided."}</p>
                    </div>
                </div>
            </div>
        </div>
    );
}

function Detail({ label, value }: { label: string; value: string }) {
    return (
        <div className="rounded-xl border border-border bg-muted/25 p-3">
            <p className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p>
            <p className="mt-1 text-[11px] font-semibold text-foreground">{value}</p>
        </div>
    );
}
