CREATE TABLE IF NOT EXISTS public.device_claim_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    claim_reference_no VARCHAR(100),
    device_sl_no VARCHAR(150) NOT NULL,

    forwarded_by_emp_id VARCHAR(50),
    received_by_emp_id VARCHAR(50),

    previous_status SMALLINT,
    current_status SMALLINT,

    remarks TEXT,

    vendor_representative VARCHAR(150),
    vendor_personnel_name VARCHAR(150),
    vendor_mobile VARCHAR(50),

    created_by VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE,

    status SMALLINT NOT NULL DEFAULT 1,

    attachment_file TEXT,

    inventory_device_id BIGINT DEFAULT 0,
    service_type SMALLINT DEFAULT 2,

    inserted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_device_claim_histories_device_sl_no
ON public.device_claim_histories (device_sl_no);

CREATE INDEX IF NOT EXISTS idx_device_claim_histories_claim_reference_no
ON public.device_claim_histories (claim_reference_no);

CREATE INDEX IF NOT EXISTS idx_device_claim_histories_current_status
ON public.device_claim_histories (current_status);

CREATE INDEX IF NOT EXISTS idx_device_claim_histories_status
ON public.device_claim_histories (status);

CREATE INDEX IF NOT EXISTS idx_device_claim_histories_created_at
ON public.device_claim_histories (created_at);