
// backend/internal/middleware/middleware.go
package middleware

import (
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
	"golang.org/x/time/rate"
)

/* ============================================================
   AUTHENTICATION CONTEXT KEYS
============================================================ */

const (
	ContextUserID     = "user_id"
	ContextEmployeeID = "employee_id"
	ContextUsername   = "username"
	ContextUserType   = "user_type"
	ContextRoleCode   = "role_code"
)

/* ============================================================
   USER TYPE / ROLE CONSTANTS

   0 = Root / Super Administrator
   1 = IT Administrator
   2 = IT Personnel
   3 = General User
============================================================ */

const (
	UserTypeRoot        = 0
	UserTypeITAdmin     = 1
	UserTypeITPersonnel = 2
	UserTypeGeneral     = 3
)

/* ============================================================
   JWT CLAIMS

   IMPORTANT:
   UserType keeps json:"role" for backward compatibility with
   the JWT tokens already generated by the current application.

   RoleCode is new and will be populated after handler/auth.go
   is upgraded in the next step.
============================================================ */

type Claims struct {
	UserID     int    `json:"uid"`
	EmployeeID string `json:"emp"`
	Username   string `json:"uname"`
	UserType   int    `json:"role"`
	RoleCode   string `json:"role_code,omitempty"`

	jwt.RegisteredClaims
}

/* ============================================================
   AUTH MIDDLEWARE
============================================================ */

func Auth(secret string) gin.HandlerFunc {
	secret = strings.TrimSpace(secret)

	return func(c *gin.Context) {
		if secret == "" {
			c.AbortWithStatusJSON(
				http.StatusInternalServerError,
				gin.H{
					"success": false,
					"error":   "authentication configuration error",
				},
			)
			return
		}

		authHeader := strings.TrimSpace(
			c.GetHeader("Authorization"),
		)

		parts := strings.Fields(authHeader)

		if len(parts) != 2 ||
			!strings.EqualFold(parts[0], "Bearer") ||
			strings.TrimSpace(parts[1]) == "" {

			c.AbortWithStatusJSON(
				http.StatusUnauthorized,
				gin.H{
					"success": false,
					"error":   "missing or invalid authorization token",
				},
			)
			return
		}

		tokenString := strings.TrimSpace(parts[1])

		claims := &Claims{}

		parser := jwt.NewParser(
			jwt.WithValidMethods(
				[]string{
					jwt.SigningMethodHS256.Alg(),
				},
			),
			jwt.WithExpirationRequired(),
			jwt.WithIssuedAt(),
			jwt.WithLeeway(30*time.Second),
		)

		token, err := parser.ParseWithClaims(
			tokenString,
			claims,
			func(token *jwt.Token) (any, error) {
				if token.Method.Alg() != jwt.SigningMethodHS256.Alg() {
					return nil, jwt.ErrSignatureInvalid
				}

				return []byte(secret), nil
			},
		)

		if err != nil || token == nil || !token.Valid {
			c.AbortWithStatusJSON(
				http.StatusUnauthorized,
				gin.H{
					"success": false,
					"error":   "invalid or expired token",
				},
			)
			return
		}

		if claims.UserID <= 0 {
			c.AbortWithStatusJSON(
				http.StatusUnauthorized,
				gin.H{
					"success": false,
					"error":   "invalid token identity",
				},
			)
			return
		}

		if strings.TrimSpace(claims.Username) == "" {
			c.AbortWithStatusJSON(
				http.StatusUnauthorized,
				gin.H{
					"success": false,
					"error":   "invalid token identity",
				},
			)
			return
		}

		if claims.UserType < UserTypeRoot ||
			claims.UserType > UserTypeGeneral {

			c.AbortWithStatusJSON(
				http.StatusUnauthorized,
				gin.H{
					"success": false,
					"error":   "invalid token role",
				},
			)
			return
		}

		c.Set(ContextUserID, claims.UserID)
		c.Set(ContextEmployeeID, strings.TrimSpace(claims.EmployeeID))
		c.Set(ContextUsername, strings.TrimSpace(claims.Username))
		c.Set(ContextUserType, claims.UserType)
		c.Set(ContextRoleCode, strings.TrimSpace(claims.RoleCode))

		c.Next()
	}
}

/* ============================================================
   AUTH CONTEXT HELPERS
============================================================ */

func GetCurrentUserID(c *gin.Context) (int, bool) {
	value, exists := c.Get(ContextUserID)
	if !exists {
		return 0, false
	}

	userID, ok := value.(int)
	if !ok || userID <= 0 {
		return 0, false
	}

	return userID, true
}

func GetCurrentEmployeeID(c *gin.Context) (string, bool) {
	value, exists := c.Get(ContextEmployeeID)
	if !exists {
		return "", false
	}

	employeeID, ok := value.(string)
	if !ok {
		return "", false
	}

	employeeID = strings.TrimSpace(employeeID)
	if employeeID == "" {
		return "", false
	}

	return employeeID, true
}

func GetCurrentUsername(c *gin.Context) (string, bool) {
	value, exists := c.Get(ContextUsername)
	if !exists {
		return "", false
	}

	username, ok := value.(string)
	if !ok {
		return "", false
	}

	username = strings.TrimSpace(username)
	if username == "" {
		return "", false
	}

	return username, true
}

func GetCurrentUserType(c *gin.Context) (int, bool) {
	value, exists := c.Get(ContextUserType)
	if !exists {
		return 0, false
	}

	userType, ok := value.(int)
	if !ok {
		return 0, false
	}

	if userType < UserTypeRoot || userType > UserTypeGeneral {
		return 0, false
	}

	return userType, true
}

func GetCurrentRoleCode(c *gin.Context) (string, bool) {
	value, exists := c.Get(ContextRoleCode)
	if !exists {
		return "", false
	}

	roleCode, ok := value.(string)
	if !ok {
		return "", false
	}

	roleCode = strings.TrimSpace(roleCode)
	if roleCode == "" {
		return "", false
	}

	return roleCode, true
}

/* ============================================================
   IP RATE LIMITER
============================================================ */

type ipRL struct {
	mu       sync.Mutex
	limiters map[string]*rate.Limiter
	r        rate.Limit
	b        int
}

func newIPRL(r rate.Limit, b int) *ipRL {
	return &ipRL{
		limiters: make(map[string]*rate.Limiter),
		r:        r,
		b:        b,
	}
}

func (l *ipRL) get(ip string) *rate.Limiter {
	l.mu.Lock()
	defer l.mu.Unlock()

	if limiter, ok := l.limiters[ip]; ok {
		return limiter
	}

	limiter := rate.NewLimiter(l.r, l.b)
	l.limiters[ip] = limiter

	return limiter
}

func RateLimit(requests float64, window time.Duration) gin.HandlerFunc {
	if requests <= 0 {
		requests = 1
	}

	if window <= 0 {
		window = time.Minute
	}

	interval := window / time.Duration(requests)

	rl := newIPRL(
		rate.Every(interval),
		int(requests),
	)

	return func(c *gin.Context) {
		if !rl.get(c.ClientIP()).Allow() {
			c.AbortWithStatusJSON(
				http.StatusTooManyRequests,
				gin.H{
					"success": false,
					"error":   "rate limit exceeded",
				},
			)
			return
		}

		c.Next()
	}
}

/* ============================================================
   REQUEST LOGGER
============================================================ */

func Logger() gin.HandlerFunc {
	return gin.LoggerWithConfig(
		gin.LoggerConfig{
			SkipPaths: []string{
				"/health",
			},
		},
	)
}
