BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS public.trouble_tickets (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id                   BIGINT UNIQUE,
    tt_no                       VARCHAR(32) NOT NULL UNIQUE,

    employee_id                 VARCHAR(32),
    employee_name               VARCHAR(200),
    designation                 VARCHAR(200),
    department                  VARCHAR(200),
    function_name               VARCHAR(200),
    company_name                VARCHAR(200),
    mobile_no                   VARCHAR(32),
    email                       VARCHAR(254),

    query_type                  VARCHAR(250),
    description                 TEXT,

    requested_by                VARCHAR(200),
    assigned_id                 VARCHAR(64),
    assigned_name               VARCHAR(200),

    status                      VARCHAR(32) NOT NULL DEFAULT 'Open',
    requisition_type            VARCHAR(200),
    delivered_status            VARCHAR(32),

    created_at                  TIMESTAMPTZ NOT NULL,
    closed_at                   TIMESTAMPTZ,
    closed_by                   VARCHAR(200),
    closing_description         TEXT,

    source_status               SMALLINT,
    source_progress             SMALLINT,
    source_device_requisition   SMALLINT,
    legacy_data                 JSONB NOT NULL DEFAULT '{}'::JSONB,

    inserted_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT trouble_tickets_status_check
        CHECK (
            status IN (
                'Not Started',
                'Open',
                'In Progress',
                'Closed'
            )
        ),

    CONSTRAINT trouble_tickets_delivery_check
        CHECK (
            delivered_status IS NULL
            OR delivered_status IN (
                'Pending',
                'Delivered',
                'Canceled'
            )
        ),

    CONSTRAINT trouble_tickets_closed_time_check
        CHECK (
            closed_at IS NULL
            OR closed_at >= created_at
        )
);

CREATE TABLE IF NOT EXISTS public.trouble_ticket_history (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id           BIGINT NOT NULL
                        REFERENCES public.trouble_tickets(id)
                        ON DELETE CASCADE,

    source_table        VARCHAR(64),
    source_legacy_id    BIGINT,

    event_type          VARCHAR(32) NOT NULL,
    previous_status     VARCHAR(32),
    current_status      VARCHAR(32),

    note                TEXT,
    assigned_from       VARCHAR(64),
    assigned_to         VARCHAR(64),
    department          VARCHAR(200),
    attachment_url      TEXT,
    changed_by          VARCHAR(200),

    legacy_data         JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    imported_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT trouble_ticket_history_source_unique
        UNIQUE (source_table, source_legacy_id),

    CONSTRAINT trouble_ticket_history_event_check
        CHECK (
            event_type IN (
                'created',
                'status_change',
                'assigned',
                'comment',
                'requisition',
                'attachment',
                'closed'
            )
        ),

    CONSTRAINT trouble_ticket_history_previous_status_check
        CHECK (
            previous_status IS NULL
            OR previous_status IN (
                'Not Started',
                'Open',
                'In Progress',
                'Closed'
            )
        ),

    CONSTRAINT trouble_ticket_history_current_status_check
        CHECK (
            current_status IS NULL
            OR current_status IN (
                'Not Started',
                'Open',
                'In Progress',
                'Closed'
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_trouble_tickets_created_at
    ON public.trouble_tickets (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_trouble_tickets_status_created
    ON public.trouble_tickets (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_trouble_tickets_employee_id
    ON public.trouble_tickets (employee_id);

CREATE INDEX IF NOT EXISTS idx_trouble_ticket_history_ticket_created
    ON public.trouble_ticket_history (ticket_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_trouble_tickets_tt_no_trgm
    ON public.trouble_tickets
    USING GIN (tt_no gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_trouble_tickets_employee_name_trgm
    ON public.trouble_tickets
    USING GIN (employee_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_trouble_tickets_query_type_trgm
    ON public.trouble_tickets
    USING GIN (query_type gin_trgm_ops);

CREATE OR REPLACE VIEW public.v_trouble_ticket_dashboard AS
SELECT
    ticket.id,
    ticket.tt_no,
    COALESCE(ticket.employee_id, '') AS employee_id,
    COALESCE(ticket.employee_name, '') AS employee_name,
    COALESCE(ticket.assigned_id, '') AS assigned_id,
    COALESCE(ticket.assigned_name, '') AS assigned_name,
    COALESCE(ticket.query_type, '') AS query_type,
    COALESCE(ticket.requisition_type, '') AS requisition_type,
    ticket.status,
    COALESCE(ticket.department, '') AS dept_name,
    COALESCE(ticket.function_name, '') AS func_name,
    COALESCE(ticket.delivered_status, '') AS delivered_status,
    ticket.created_at,
    ticket.closed_at,
    GREATEST(
        0,
        EXTRACT(
            EPOCH FROM (
                COALESCE(ticket.closed_at, CURRENT_TIMESTAMP)
                - ticket.created_at
            )
        )::BIGINT
    ) AS age_seconds,
    COALESCE(ticket.mobile_no, '') AS mobile_no,
    COALESCE(ticket.company_name, '') AS company_name
FROM public.trouble_tickets AS ticket;

COMMIT;
